final/final/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

from home.views import home, patient, doctor, pharmacist, insurance
# from home import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    # path('', RedirectView.as_view(url='/home/')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', home.SignUpView.as_view(), name='signup'),
    path('accounts/signup/patient/', patient.PatientSignUpView.as_view(), name='patient_signup'),
    path('accounts/signup/doctor/', doctor.DoctorSignUpView.as_view(), name='doctor_signup'),
    path('accounts/signup/pharmacist/', pharmacist.PharmacistSignUpView.as_view(), name='pharmacist_signup'),
    path('accounts/signup/insurance/', insurance.InsuranceSignUpView.as_view(), name='insurance_signup'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

final/home/urls.py
from django.urls import path, include
from .views import home, patient, doctor, pharmacist, insurance

urlpatterns = [
    path('', home.index, name='index'),

    path('patient/', include(([
        path('pro/', patient.PatientListView.as_view(), name='patient_list'),
        path('pro/profile/<int:pk>', patient.PatientProfileView.as_view(), name='patient_profile'),
        path('pro/<int:pk>', patient.PatientDetailView.as_view(), name='patient_detail'),
        path('pro/profile/<int:pk>/edit/<int:ppk>', patient.PatientProfileUpdateView.as_view(), name='patient_edit'),
        path('pro/profile/<int:pk>/viewbill/<int:ppk>', patient.PatientBillDetailView.as_view(), name='patient_bill'),
        path('pro/profile/<int:pk>/viewbill/<int:ppk>/confirmbill', patient.PatientBillConfirmUpdateView.as_view(), name='patient_confirm_bill'),
    ], 'home'), namespace='patient')),

    path('doctor/', include(([
        path('doc/', doctor.DoctorListView.as_view(), name='doctor_list'),
        path('doc/profile/<int:pk>/', doctor.DoctorProfileView.as_view(), name='doctor_profile'),
        path('doc/<int:pk>/', doctor.DoctorDetailView.as_view(), name='doctor_detail'),
        path('doc/<int:pk>/prescription/add/', doctor.PrescriptionCreateView.as_view(), name='doctor_addpresc'),
        path('doc/<int:pk>/prescription/<int:ppk>/delete/', doctor.PrescriptionDeleteView.as_view(), name='prescription_confirm_delete'),
        path('doc/<int:pk>/prescription/<int:ppk>/edit/', doctor.PrescriptionUpdateView.as_view(), name='prescription_edit'),
    ], 'home'), namespace='doctor')),
    
    
    path('pharmacist/', include(([
        path('pha/', pharmacist.PharmacistListView.as_view(), name='pharmacist_list'),
        path('pha/profile/<int:pk>/', pharmacist.PharmacistProfileView.as_view(), name='pharmacist_profile'),
        path('pha/<int:pk>/', pharmacist.PharmacistDetailView, name='pharmacist_detail'),
    ], 'home'), namespace='pharmacist')),
    
    
    path('insurance/', include(([
        path('ins/', insurance.InsuranceListView.as_view(), name='insurance_list'),
        path('ins/<int:pk>/patient/', insurance.InsuranceDetailView, name='insurance_detail'),
        path('ins/<int:pk>/bills/', insurance.InsurancePatientBillsView, name='insurance_patient'),
        path('ins/<int:pk>/bills/<int:ppk>/', insurance.InsuranceBillDetailView.as_view(), name='insurance_bills'),
    ], 'home'), namespace='insurance')),
]

final/home/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save


class User(AbstractUser):
    is_patient = models.BooleanField(default=False)
    is_doctor = models.BooleanField(default=False)
    is_pharmacist = models.BooleanField(default=False)
    is_insurance = models.BooleanField(default=False)

    
class Patient(models.Model):
    """model representing patient"""
    GENDER_CHOICES = [('M', 'Male'), ('F', 'Female')]
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    ssn = models.IntegerField('SSN', blank=False, primary_key=True)
    first_name = models.CharField('First Name', max_length=50, blank=False)
    last_name = models.CharField('Last Name', max_length=50, blank=False)
    email = models.EmailField('Email', max_length=40, blank=True, null=True, unique=True)
    gender = models.CharField(max_length=3, choices=GENDER_CHOICES, default='M')
    phone = models.IntegerField('Phone Number', blank=True, null=True)
    creditcard = models.IntegerField('Credit Card Number', blank=True, null=True)
    
    class Meta:
        ordering = ['ssn']

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}'

    def get_absolute_url(self):
        """Returns the url to access a detail record for this patient."""
        return reverse('patient:patient_detail', args=[str(self.ssn)])

def create_profile(sender, **kwargs):
    if kwargs['created']:
        patient = Patient.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)
    

    
class Insurance(models.Model):
    # for insurance info
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    ssn = models.IntegerField('SSN', blank=False, primary_key=True)
    name = models.CharField('Name', max_length=50, blank=True)
    
    class Meta:
        ordering = ['ssn']
        
    def __str__(self):
        return f'{self.name}'
    
    def get_absolute_url(self):
        return reverse('insurance:insurance_detail', args=[str(self.ssn)])

def create_profile_ins(sender, **kwargs):
    if kwargs['created']:
        insurance = Insurance.objects.create(user=kwargs['instance'])

post_save.connect(create_profile_ins, sender=User)

class Pharmacist(models.Model):
    # for pharmacist info
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    ssn = models.IntegerField('SSN', blank=False, primary_key=True)
    name = models.CharField('Name', max_length=50, blank=True)
    
    class Meta:
        ordering = ['ssn']

    def __str__(self):
        return f'{self.ssn} {self.name}'
    
    def get_absolute_url(self):
        return reverse('pharmacist:pharmacist_detail', args=[str(self.ssn)])

def create_profile_pha(sender, **kwargs):
    if kwargs['created']:
        pharmacist = Pharmacist.objects.create(user=kwargs['instance'])

post_save.connect(create_profile_pha, sender=User)
    
    
class Doctor(models.Model):
    # model representing doctor
    GENDER_CHOICES = [('M', 'Male'), ('F', 'Female')]
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    ssn = models.IntegerField('SSN', blank=False, primary_key=True)
    first_name = models.CharField('First Name', max_length=50, blank=False)
    last_name = models.CharField('Last Name', max_length=50, blank=False)
    gender = models.CharField(max_length=3, choices=GENDER_CHOICES, default='M')
    email = models.EmailField('Email', max_length=40, blank=True, null=True, unique=True)
    specialty = models.CharField(max_length=50, default='ENT')

    def __str__(self):
        return f'{self.first_name} {self.last_name} ({self.specialty})'

    class Meta:
        ordering = ['ssn']

    def get_absolute_url(self):
        return reverse('doctor:doctor_detail', args=[str(self.ssn)])

def create_profile_doc(sender, **kwargs):
    if kwargs['created']:
        doctor = Doctor.objects.create(user=kwargs['instance'])

post_save.connect(create_profile_doc, sender=User)


class Prescription(models.Model):
    # model representing prescription
    patient = models.ForeignKey(Patient, on_delete=models.SET_NULL, null=True)
    doctor = models.ForeignKey(Doctor, on_delete=models.SET_NULL, null=True)
    dop = models.DateField('Prescription Date', null=True, blank=False)
    desc = models.CharField('Prescription Details', null=True, max_length=150)

    class Meta:
        ordering = ['patient', '-dop']

    def __str__(self):
        return f'{self.patient} {self.doctor} {self.desc}'

    def get_absolute_url(self):
        return reverse('doctor:doctor_detail', args=[str(self.doctor.ssn)])

final/home/views/doctor.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import (CreateView, ListView, DeleteView, DetailView, UpdateView)
from django.contrib.messages.views import SuccessMessageMixin

from ..decorators import doctor_required
from ..forms import DoctorSignUpForm
from ..models import Doctor, User, Prescription


class DoctorSignUpView(CreateView):
    model = User
    form_class = DoctorSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'doctor'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('doctor:doctor_list')


@method_decorator([login_required, doctor_required], name='dispatch')
class DoctorDetailView(DetailView):
    model = Doctor
    template_name = 'home/doctor/doctor_detail.html'


@method_decorator([login_required, doctor_required], name='dispatch')
class DoctorListView(ListView):
    model = Doctor
    template_name = 'home/doctor/doctor_list.html'

    
@method_decorator([login_required, doctor_required], name='dispatch')
class DoctorProfileView(DetailView):
    model = Doctor
    template_name = 'home/doctor/doctor_profile.html'
    

@method_decorator([login_required, doctor_required], name='dispatch')
class PrescriptionCreateView(CreateView):
    model = Prescription
    fields = ('patient', 'dop', 'desc', )
    template_name = 'home/doctor/doctor_addpresc.html'

    
    def form_valid(self, form):
        form.instance.doctor = self.request.user.doctor
        return super().form_valid(form)


    
@method_decorator([login_required, doctor_required], name='dispatch')
class PrescriptionDeleteView(DeleteView):
    model = Prescription
    context_object_name = 'prescription'
    template_name = 'home/doctor/prescription_confirm_delete.html'
    pk_url_kwarg = 'ppk'
    
    def delete(self, request, *args, **kwargs):
        prescription = self.get_object()
        messages.success(request, 'The prescription of "%s" was deleted with success!' % prescription.patient)
        return super().delete(request, *args, **kwargs)
    
    def get_queryset(self):
        return Prescription.objects.filter(doctor = self.request.user.doctor)
    
    def get_success_url(self):
        doc = self.object.doctor
        return reverse_lazy('doctor:doctor_detail', kwargs={'pk': doc.ssn})
    
@method_decorator([login_required, doctor_required], name='dispatch')
class PrescriptionUpdateView(UpdateView):
    model = Prescription
    fields = ('dop', 'desc',)
    context_object_name = 'prescription'
    template_name = 'home/doctor/prescription_edit.html'
    pk_url_kwarg = 'ppk'
    
    def get_queryset(self):
        return Prescription.objects.filter(doctor = self.request.user.doctor)
    
    def get_success_url(self):
        doc = self.object.doctor
        return reverse_lazy('doctor:doctor_detail', kwargs={'pk': doc.ssn})

final/home/views/home.py
from django.shortcuts import redirect, render
from django.views.generic import TemplateView


class SignUpView(TemplateView):
    template_name = 'registration/signup.html'


def index(request):
        
    if request.user.is_authenticated:
        if request.user.is_doctor:
            return redirect('doctor:doctor_list')
        elif request.user.is_patient:
            return redirect('patient:patient_list')
        elif request.user.is_pharmacist:
            return redirect('pharmacist:pharmacist_list')
        else:
            return redirect('insurance:insurance_list')
    return render(request, 'home/index.html')

final/home/views/insurance.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import (CreateView, ListView, DeleteView, DetailView, UpdateView)
from django.contrib.messages.views import SuccessMessageMixin

from ..decorators import insurance_required
from ..forms import InsuranceSignUpForm
from ..models import Insurance, User, Prescription, Patient


class InsuranceSignUpView(CreateView):
    model = User
    form_class = InsuranceSignUpForm
    template_name = 'registration/signup_form.html'
    
    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'insurance'
        return super().get_context_data(**kwargs)
    
    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('insurance:insurance_list')
    
@login_required
@insurance_required
def InsuranceDetailView(request, pk):
    pat_all = Patient.objects.all()
    template_name = 'home/insurance/insurance_detail.html'
    
    return render(request, template_name, context = {'pat_all': pat_all},)


@method_decorator([login_required, insurance_required], name='dispatch')
class InsuranceListView(ListView):
    model = Insurance
    template_name = 'home/insurance/insurance_list.html'
    
@login_required
@insurance_required
def InsurancePatientBillsView(request, pk):
    pat_all = Prescription.objects.all()
    template_name = 'home/insurance/insurance_patient.html'
    
    return render(request, template_name, context = {'pat_all': pat_all},)

@method_decorator([login_required, insurance_required], name='dispatch')
class InsuranceBillDetailView(DetailView):
    model = Prescription
    template_name = 'home/insurance/insurance_bills.html'

final/home/views/patient.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, UpdateView, DetailView, DeleteView, FormView
from django.contrib.messages.views import SuccessMessageMixin

from ..decorators import patient_required
from ..forms import PatientSignUpForm
from ..models import Patient, User, Prescription


class PatientSignUpView(CreateView):
    model = User
    form_class = PatientSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'patient'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('patient:patient_list')


@method_decorator([login_required, patient_required], name='dispatch')
class PatientListView(ListView):
    model = Patient
    template_name = 'home/patient/patient_list.html'

    def get_queryset(self):
        return Patient.objects.all()


@method_decorator([login_required, patient_required], name='dispatch')
class PatientDetailView(DetailView):
    model = Patient
    template_name = 'home/patient/patient_detail.html'


@method_decorator([login_required, patient_required], name='dispatch')
class PatientProfileView(DetailView):
    model = Patient
    template_name = 'home/patient/patient_profile.html'
    
    
@method_decorator([login_required, patient_required], name='dispatch')
class PatientProfileUpdateView(SuccessMessageMixin, UpdateView):
    model = Patient
    fields = ('email','phone','creditcard',)
    template_name = 'home/patient/patient_edit.html'
    pk_url_kwarg = 'ppk'
    success_message = 'Profile Edited Successfully!!'
    
    def get_queryset(self):
        return Patient.objects.filter(ssn=self.request.user.patient.ssn)
        
    def get_success_url(self):
        return reverse_lazy('patient:patient_profile', kwargs={'pk': self.request.user.patient.ssn})

@method_decorator([login_required, patient_required], name='dispatch')
class PatientBillDetailView(DetailView):
    model = Prescription
    template_name = 'home/patient/patient_bill.html'
    context_object_name = 'prescription'
    pk_url_kwarg = 'ppk'
    
    def get_queryset(self):
        return Prescription.objects.filter(patient = self.request.user.patient)

@method_decorator([login_required, patient_required], name='dispatch')
class PatientBillConfirmUpdateView(SuccessMessageMixin, UpdateView):
    model = Patient
    fields = ('creditcard',)
    template_name = 'home/patient/patient_confirm_bill.html'
    pk_url_kwarg = 'ppk'
    
    success_message = 'Bill Paid!!!'
    
    def get_queryset(self):
        return Patient.objects.filter(ssn=self.request.user.patient.ssn)
    
    def get_success_url(self):
        return reverse_lazy('patient:patient_detail', kwargs={'pk': self.request.user.patient.ssn})
    

final/home/templates/home/doctor/11.html
<h1><strong>lol</strong></h1>

final/home/templates/home/doctor/doctor_addpresc.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h2>Add a new Prescription</h2>
<div class="row">
    <div class="col-md-6 col-sm-8 col-12">
        <form method="post" novalidate>
            {% csrf_token %}
            {{form | crispy }}
            <button type="submit" class="btn btn-sucess">Save</button>
            <a href="{% url 'doctor:doctor_list' %}" class="btn btn-outline-secondary" role="button">Nevermind</a>
        </form>
    </div>
</div>
{% endblock %}

final/home/templates/home/doctor/doctor_detail.html
<!DOCTYPE html>

{% extends "base.html" %}

{% block content %}
<style>
table, td, th {  
  border: 2px solid #ddd;
  text-align: left;
}

table {
  border-collapse: collapse;
  width: 100%;
}

th, td {
  padding: 10px;
}
</style>
<h2>ALL PRESCRIPTIONS</h2>
<div class="card" style="margin-left: 10px; margin-top: 20px">
    <table class="table mb-0" style="table-layout: auto">
     <thead>
        <tr>
          <th class="align-middle">PRESC. ID</th>    
          <th class="align-middle">PATIENT</th>
          <th class="align-middle">PRESCRIPTION DATE</th>
          <th class="align-middle">PRESCRIPTION DETAILS</th>
          <th class="align-middle" colspan="2">&nbsp;</th>    
        </tr>
      </thead>
      <tbody>
        {% for p in user.doctor.prescription_set.all %}
          <tr>
            <td class="align-middle" style="text-align: left">{{p.id}}</td>
            <td class="align-middle" style="text-align: left">{{p.patient}}</td>
            <td class="align-middle" style="text-align: left">{{p.dop}}</td>
            <td class="align-middle" style="text-align: left">{{p.desc}}</td>
            <td class="align-middle">
              <a href="{% url 'doctor:prescription_edit' user.doctor.ssn p.id %}" class="btn btn-warning">Edit</a> 
            </td>
            <td class="align-middle">
                <a href="{% url 'doctor:prescription_confirm_delete' user.doctor.ssn p.id %}" class="btn btn-danger">Delete</a>
            </td>    
          </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="6">There are no prescriptions.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

final/home/templates/home/doctor/doctor_list.html
<!DOCTYPE html>
{% extends "base.html" %}

{% block content %}
<br>
<div class="container-fluid">
    <div class="row">
        <ul style="list-style-type:none" class="col-3 text-left">
            <li><a href="{% url 'doctor:doctor_profile' user.doctor.ssn %}" class="btn btn-outline-primary" role="button"><strong>Profile</strong></a></li>
            <li><a href="{% url 'doctor:doctor_detail' user.doctor.ssn %}" class="btn btn-outline-primary" role="button"><strong>All Prescriptions</strong></a></li>
            <li><a href="{% url 'doctor:doctor_addpresc' user.doctor.ssn %}" class="btn btn-outline-primary" role="button"><strong>Add Prescription</strong></a></li>
        </ul>
        <div style="margin-left: 20px">
            <h1> Welcome, Dr {{ user.doctor.first_name }} {{ user.doctor.last_name}}</h1>    
        </div>
    </div>
</div>
{% endblock %}

final/home/templates/home/doctor/doctor_presc_confirm_delete.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<h2 class="mb-3">Confirm deletion</h2>
<p class="lead">Are you sure you want to delete this <strong>"{{ user.prescription.patient }}"</strong> patient's prescription?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger btn-lg">Yes, I'm sure</button>
        <a href="{% url 'doctor:doctor_detail' doctor.ssn %}" class="btn btn-outline-secondary btn-lg" role="button">Nevermind</a>
    </form>
{% endblock %}

final/home/templates/home/doctor/doctor_profile.html
<!DOCTYPE html>

{% extends "base.html" %}

{% block content %}
<div style="margin-left:20px;">
    <h2>Dr {{ user.doctor.first_name }} {{ user.doctor.last_name}}</h2>
    <p><strong>SSN: </strong> {{ user.doctor.ssn }}</p>
    <p><strong>Email: </strong>{{ user.doctor.email }}</p>
    <p><strong>Gender: </strong>{{ user.doctor.gender }}</p>
    <p><strong>Specialty: </strong> {{ user.doctor.specialty }}</p>
</div>
{% endblock %}

final/home/templates/home/doctor/prescription_confirm_delete.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<h2 class="mb-3">Confirm deletion</h2>
<p class="lead">Are you sure you want to delete <strong><b>{{ prescription.patient }}</b></strong>'s prescription?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger btn-lg">Yes, I'm sure</button>
        <a href="{% url 'doctor:doctor_detail' user.doctor.ssn %}" class="btn btn-outline-secondary btn-lg" role="button">Nevermind</a>
    </form>
{% endblock %}

final/home/templates/home/doctor/prescription_edit.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<h2>Edit Prescription</h2>
<div class="row">
    <div class="col-md-6 col-sm-8 col-12">
       <form method="post" novalidate>
           {% csrf_token %}
           {{form | crispy }}
           <button type="submit" class="btn btn-sucess">Save</button>
           <a href="{% url 'doctor:doctor_list' %}" class="btn btn-outline-secondary" role="button">Nevermind</a>
       </form>
    </div>
</div>
{% endblock %}