final/final/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

from home.views import home, patient, doctor, pharmacist, insurance
# from home import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    # path('', RedirectView.as_view(url='/home/')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', home.SignUpView.as_view(), name='signup'),
    path('accounts/signup/patient/', patient.PatientSignUpView.as_view(), name='patient_signup'),
    path('accounts/signup/doctor/', doctor.DoctorSignUpView.as_view(), name='doctor_signup'),
    path('accounts/signup/pharmacist/', pharmacist.PharmacistSignUpView.as_view(), name='pharmacist_signup'),
    path('accounts/signup/insurance/', insurance.InsuranceSignUpView.as_view(), name='insurance_signup'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

final/home/urls.py
from django.urls import path, include
from .views import home, patient, doctor, pharmacist, insurance

urlpatterns = [
    path('', home.index, name='index'),

    path('patient/', include(([
        path('pro/', patient.PatientListView.as_view(), name='patient_list'),
        path('pro/profile/<int:pk>', patient.PatientProfileView.as_view(), name='patient_profile'),
        path('pro/<int:pk>', patient.PatientDetailView.as_view(), name='patient_detail'),
        path('pro/profile/<int:pk>/edit/<int:ppk>', patient.PatientProfileUpdateView.as_view(), name='patient_edit'),
        path('pro/profile/<int:pk>/viewbill/<int:ppk>', patient.PatientBillDetailView.as_view(), name='patient_bill'),
        path('pro/profile/<int:pk>/viewbill/<int:ppk>/confirmbill', patient.PatientBillConfirmUpdateView.as_view(), name='patient_confirm_bill'),
    ], 'home'), namespace='patient')),

    path('doctor/', include(([
        path('doc/', doctor.DoctorListView.as_view(), name='doctor_list'),
        path('doc/profile/<int:pk>/', doctor.DoctorProfileView.as_view(), name='doctor_profile'),
        path('doc/<int:pk>/', doctor.DoctorDetailView.as_view(), name='doctor_detail'),
        path('doc/<int:pk>/prescription/add/', doctor.PrescriptionCreateView.as_view(), name='doctor_addpresc'),
        path('doc/<int:pk>/prescription/<int:ppk>/delete/', doctor.PrescriptionDeleteView.as_view(), name='prescription_confirm_delete'),
        path('doc/<int:pk>/prescription/<int:ppk>/edit/', doctor.PrescriptionUpdateView.as_view(), name='prescription_edit'),
    ], 'home'), namespace='doctor')),
    
    
    path('pharmacist/', include(([
        path('pha/', pharmacist.PharmacistListView.as_view(), name='pharmacist_list'),
        path('pha/profile/<int:pk>/', pharmacist.PharmacistProfileView.as_view(), name='pharmacist_profile'),
        path('pha/<int:pk>/', pharmacist.PharmacistDetailView, name='pharmacist_detail'),
    ], 'home'), namespace='pharmacist')),
    
    
    path('insurance/', include(([
        path('ins/', insurance.InsuranceListView.as_view(), name='insurance_list'),
        path('ins/<int:pk>/patient/', insurance.InsuranceDetailView, name='insurance_detail'),
        path('ins/<int:pk>/bills/', insurance.InsurancePatientBillsView, name='insurance_patient'),
        path('ins/<int:pk>/bills/<int:ppk>/', insurance.InsuranceBillDetailView.as_view(), name='insurance_bills'),
    ], 'home'), namespace='insurance')),
]

final/home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from django.forms.utils import ValidationError

from home.models import (User, Patient, Doctor, Pharmacist, Insurance)


class DoctorSignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'password1',
            'password2'
        )

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_doctor = True
        if commit:
            user.save()
        return user


class PatientSignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'password1',
            'password2'
        )
        
    @transaction.atomic    
    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_patient = True
        if commit:
            user.save()
        return user
    

class PharmacistSignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'password1',
            'password2'
        )
        
    @transaction.atomic    
    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_pharmacist = True
        if commit:
            user.save()
        return user
    

class InsuranceSignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'password1',
            'password2'
        )
        
    @transaction.atomic    
    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_insurance = True
        if commit:
            user.save()
        return user

final/home/views/doctor.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import (CreateView, ListView, DeleteView, DetailView, UpdateView)
from django.contrib.messages.views import SuccessMessageMixin

from ..decorators import doctor_required
from ..forms import DoctorSignUpForm
from ..models import Doctor, User, Prescription


class DoctorSignUpView(CreateView):
    model = User
    form_class = DoctorSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'doctor'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('doctor:doctor_list')


@method_decorator([login_required, doctor_required], name='dispatch')
class DoctorDetailView(DetailView):
    model = Doctor
    template_name = 'home/doctor/doctor_detail.html'


@method_decorator([login_required, doctor_required], name='dispatch')
class DoctorListView(ListView):
    model = Doctor
    template_name = 'home/doctor/doctor_list.html'

    
@method_decorator([login_required, doctor_required], name='dispatch')
class DoctorProfileView(DetailView):
    model = Doctor
    template_name = 'home/doctor/doctor_profile.html'
    

@method_decorator([login_required, doctor_required], name='dispatch')
class PrescriptionCreateView(CreateView):
    model = Prescription
    fields = ('patient', 'dop', 'desc', )
    template_name = 'home/doctor/doctor_addpresc.html'

    
    def form_valid(self, form):
        form.instance.doctor = self.request.user.doctor
        return super().form_valid(form)


    
@method_decorator([login_required, doctor_required], name='dispatch')
class PrescriptionDeleteView(DeleteView):
    model = Prescription
    context_object_name = 'prescription'
    template_name = 'home/doctor/prescription_confirm_delete.html'
    pk_url_kwarg = 'ppk'
    
    def delete(self, request, *args, **kwargs):
        prescription = self.get_object()
        messages.success(request, 'The prescription of "%s" was deleted with success!' % prescription.patient)
        return super().delete(request, *args, **kwargs)
    
    def get_queryset(self):
        return Prescription.objects.filter(doctor = self.request.user.doctor)
    
    def get_success_url(self):
        doc = self.object.doctor
        return reverse_lazy('doctor:doctor_detail', kwargs={'pk': doc.ssn})
    
@method_decorator([login_required, doctor_required], name='dispatch')
class PrescriptionUpdateView(UpdateView):
    model = Prescription
    fields = ('dop', 'desc',)
    context_object_name = 'prescription'
    template_name = 'home/doctor/prescription_edit.html'
    pk_url_kwarg = 'ppk'
    
    def get_queryset(self):
        return Prescription.objects.filter(doctor = self.request.user.doctor)
    
    def get_success_url(self):
        doc = self.object.doctor
        return reverse_lazy('doctor:doctor_detail', kwargs={'pk': doc.ssn})

final/home/views/home.py
from django.shortcuts import redirect, render
from django.views.generic import TemplateView


class SignUpView(TemplateView):
    template_name = 'registration/signup.html'


def index(request):
        
    if request.user.is_authenticated:
        if request.user.is_doctor:
            return redirect('doctor:doctor_list')
        elif request.user.is_patient:
            return redirect('patient:patient_list')
        elif request.user.is_pharmacist:
            return redirect('pharmacist:pharmacist_list')
        else:
            return redirect('insurance:insurance_list')
    return render(request, 'home/index.html')

final/home/views/insurance.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import (CreateView, ListView, DeleteView, DetailView, UpdateView)
from django.contrib.messages.views import SuccessMessageMixin

from ..decorators import insurance_required
from ..forms import InsuranceSignUpForm
from ..models import Insurance, User, Prescription, Patient


class InsuranceSignUpView(CreateView):
    model = User
    form_class = InsuranceSignUpForm
    template_name = 'registration/signup_form.html'
    
    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'insurance'
        return super().get_context_data(**kwargs)
    
    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('insurance:insurance_list')
    
@login_required
@insurance_required
def InsuranceDetailView(request, pk):
    pat_all = Patient.objects.all()
    template_name = 'home/insurance/insurance_detail.html'
    
    return render(request, template_name, context = {'pat_all': pat_all},)


@method_decorator([login_required, insurance_required], name='dispatch')
class InsuranceListView(ListView):
    model = Insurance
    template_name = 'home/insurance/insurance_list.html'
    
@login_required
@insurance_required
def InsurancePatientBillsView(request, pk):
    pat_all = Prescription.objects.all()
    template_name = 'home/insurance/insurance_patient.html'
    
    return render(request, template_name, context = {'pat_all': pat_all},)

@method_decorator([login_required, insurance_required], name='dispatch')
class InsuranceBillDetailView(DetailView):
    model = Prescription
    template_name = 'home/insurance/insurance_bills.html'

final/home/views/patient.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, UpdateView, DetailView, DeleteView, FormView
from django.contrib.messages.views import SuccessMessageMixin

from ..decorators import patient_required
from ..forms import PatientSignUpForm
from ..models import Patient, User, Prescription


class PatientSignUpView(CreateView):
    model = User
    form_class = PatientSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'patient'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('patient:patient_list')


@method_decorator([login_required, patient_required], name='dispatch')
class PatientListView(ListView):
    model = Patient
    template_name = 'home/patient/patient_list.html'

    def get_queryset(self):
        return Patient.objects.all()


@method_decorator([login_required, patient_required], name='dispatch')
class PatientDetailView(DetailView):
    model = Patient
    template_name = 'home/patient/patient_detail.html'


@method_decorator([login_required, patient_required], name='dispatch')
class PatientProfileView(DetailView):
    model = Patient
    template_name = 'home/patient/patient_profile.html'
    
    
@method_decorator([login_required, patient_required], name='dispatch')
class PatientProfileUpdateView(SuccessMessageMixin, UpdateView):
    model = Patient
    fields = ('email','phone','creditcard',)
    template_name = 'home/patient/patient_edit.html'
    pk_url_kwarg = 'ppk'
    success_message = 'Profile Edited Successfully!!'
    
    def get_queryset(self):
        return Patient.objects.filter(ssn=self.request.user.patient.ssn)
        
    def get_success_url(self):
        return reverse_lazy('patient:patient_profile', kwargs={'pk': self.request.user.patient.ssn})

@method_decorator([login_required, patient_required], name='dispatch')
class PatientBillDetailView(DetailView):
    model = Prescription
    template_name = 'home/patient/patient_bill.html'
    context_object_name = 'prescription'
    pk_url_kwarg = 'ppk'
    
    def get_queryset(self):
        return Prescription.objects.filter(patient = self.request.user.patient)

@method_decorator([login_required, patient_required], name='dispatch')
class PatientBillConfirmUpdateView(SuccessMessageMixin, UpdateView):
    model = Patient
    fields = ('creditcard',)
    template_name = 'home/patient/patient_confirm_bill.html'
    pk_url_kwarg = 'ppk'
    
    success_message = 'Bill Paid!!!'
    
    def get_queryset(self):
        return Patient.objects.filter(ssn=self.request.user.patient.ssn)
    
    def get_success_url(self):
        return reverse_lazy('patient:patient_detail', kwargs={'pk': self.request.user.patient.ssn})
    

final/home/views/pharmacist.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import (CreateView, ListView, DeleteView, DetailView, UpdateView)
from django.contrib.messages.views import SuccessMessageMixin

from ..decorators import pharmacist_required
from ..forms import PharmacistSignUpForm
from ..models import Pharmacist, User, Prescription


class PharmacistSignUpView(CreateView):
    model = User
    form_class = PharmacistSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'pharmacist'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('pharmacist:pharmacist_list')
    
    
@login_required
@pharmacist_required
def PharmacistDetailView(request, pk):
    pres_all = Prescription.objects.all()
    template_name = 'home/pharmacist/pharmacist_detail.html'
    
    return render(request, template_name, context={'pres_all': pres_all},)


@method_decorator([login_required, pharmacist_required], name='dispatch')
class PharmacistListView(ListView):
    model = Pharmacist
    template_name = 'home/pharmacist/pharmacist_list.html'
    

@method_decorator([login_required, pharmacist_required], name='dispatch')
class PharmacistProfileView(DetailView):
    model = Pharmacist
    template_name = 'home/pharmacist/pharmacist_profile.html'
    
    

final/home/templates/home/insurance/insurance_bills.html
<!DOCTYPE html>

{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<h2 style="text-align: center">BILL DETAILS</h2>
<div style="margin: 20px 100px;border:solid;padding: 20px">
    <div style="padding-bottom: 15px">
        <table style="width: 130%">
            <tr>
                <td>Patient Name: {{prescription.patient}}</td>
                <td><strong><u>Bill Date: {{prescription.dop}}</u></strong></td>
            </tr> 
        </table>
    </div>
    <div style="padding-right: 80px">
        <p>Prescription Date: {{prescription.dop}}</p>
        <p>Insurance: {{prescription.patient.ins}}</p>
        <p>Doctor: {{prescription.doctor}}</p>
        <p>Prescription Details:</p>
        <table style="width: 100%">
            <tr>
                <td><strong>{{prescription.desc}}</strong></td>
                <td style="text-align: right">Total: $ 10.00</td>
            </tr>
        </table>
    </div>
</div>

<div>
    <p style="text-align: center;padding-top: -90px"><a href="{% url 'patient:patient_confirm_bill' user.patient.ssn user.patient.ssn%}" class="btn btn-primary" role="button"><strong>Pay Now</strong></a></p>
</div>



{% endblock %}

final/home/templates/home/insurance/insurance_detail.html
<!DOCTYPE html>

{% extends "base.html" %}

{% block content %}
<style>
table, th, td {  
  border: 2px solid #ddd;
}

table {
  border-collapse: collapse;
  width: 100%;
}

th, td {
    padding: 0px;
}
</style>

<h2>PATIENT LIST</h2>
<div class="card" style="margin-left: 10px; margin-top: 20px">
    <table class="table mb-0" style="table-layout: auto">
      <thead>
        <tr>
          <th style="text-align: center">NAME</th>
          <th style="text-align: center">EMAIL</th>
          <th style="text-align: center">PHONE</th>
          <th style="text-align: center">GENDER</th>
        </tr>
      </thead>    
      <tbody>
        {% for p in pat_all %}
          <tr>
            <td class="align-middle" style="text-align: center">{{p.first_name}} {{p.last_name}}</td>
            <td class="align-middle" style="text-align: center">{{p.email}}</td>
            <td class="align-middle" style="text-align: center">{{p.phone}}</td>
            <td class="align-middle" style="text-align: center">{{p.gender}}</td>  
          </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="6">There are no patients.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>



{% endblock %}

final/home/templates/home/insurance/insurance_list.html
<!DOCTYPE html>
{% extends "base.html" %}

{% block content %}
<br>
<div class="container-fluid">
    <div class="row">
        <ul style="list-style-type:none" class="col-3 text-left">
            <li><a href="{% url 'insurance:insurance_detail' user.insurance.ssn %}" class="btn btn-outline-primary" role="button"><strong>All Patients</strong></a></li>
            <li><a href="{% url 'insurance:insurance_patient' user.insurance.ssn %}" class="btn btn-outline-primary" role="button"><strong>All Billing Details</strong></a></li>
        </ul>
        <div style="margin-left: 20px">
            <h1> Welcome, {{ user.insurance.name }} Insurance</h1>    
        </div>
    </div>
</div>
{% endblock %}

final/home/templates/home/insurance/insurance_patient.html
<!DOCTYPE html>
{% extends "base.html" %}

{% block content %}


<style>
table, th, td {  
  border: 2px solid #ddd;
}

table {
  border-collapse: collapse;
  width: 100%;
}

th, td {
    padding: 0px;
}
</style>

<h2>TREATMENT COST</h2>
<div class="card" style="margin-left: 10px; margin-top: 20px">
    <table class="table mb-0" style="table-layout: auto">
      <thead>
        <tr>
          <th style="text-align: center">NAME</th>
          <th style="text-align: center">PRESC. DATE</th>
          <th style="text-align: center">TREATMENT COST</th>
        </tr>
      </thead>    
      <tbody>
        {% for p in pat_all %}
          <tr>
            <td class="align-middle" style="text-align: center">{{p.patient}}</td>
            <td class="align-middle" style="text-align: center">{{p.dop}}</td>
            <td class="align-middle" style="text-align: center"> $10.00</td>
          </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="6">There are no patients.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>


{% endblock %}